CREATE TABLE IF NOT EXISTS 'VereinsAbteilung' (
	'VA_ID' INTEGER PRIMARY KEY AUTOINCREMENT,
	'Name' char(50)
);

CREATE TABLE IF NOT EXISTS 'Mitglied'(
	'M_ID' INTEGER PRIMARY KEY AUTOINCREMENT,
	'Vorname' char(50) NOT NULL,
	'Nachname' char(50) NOT NULL,
	'TelefonNR' char(20),
	'E-Mail' char(50) NOT NULL,
	'Adresse' char(100) NOT NULL,
	'Abteilungs_ID' INT DEFAULT NULL,
	'Passwort' char(10) NOT NULL,
	'Verwalter' int(1) NOT NULL,
	FOREIGN KEY('Abteilungs_ID') REFERENCES VereinsAbteilung(VA_ID)
);

CREATE TABLE IF NOT EXISTS 'PassivMitglied'(
	'PM_ID' INTEGER PRIMARY KEY AUTOINCREMENT,
	'inaktivSeit' date NOT NULL,
	'M_ID' INT NOT NULL,
	FOREIGN KEY('M_ID') REFERENCES Mitglied('M_ID')
);

CREATE TABLE IF NOT EXISTS 'Trainer'(
	'T_ID' INTEGER PRIMARY KEY AUTOINCREMENT,
	'kompBereich' char(50) NOT NULL,
	'M_ID' INT NOT NULL,
	FOREIGN KEY('M_ID') REFERENCES Mitglied('M_ID')
);

CREATE TABLE IF NOT EXISTS 'EhemaligesMitglied'(
	'EM_ID' INTEGER PRIMARY KEY AUTOINCREMENT,
	'ausgetretenAm' date NOT NULL,
	'M_ID' INT NOT NULL,
	FOREIGN KEY('M_ID') REFERENCES Mitglied('M_ID')
);

